version: '3'
services:
  db:
    image: mongo
    ports:
      - '27017:27017'
  graphql:
    image: graphql-demo
    build:
      context: .
    depends_on:
      - db
    ports:
      - '4000:4000'
    environment:
      - MONGO_URL=mongodb://db:27017/graphqldemo